services:
  db:
    container_name: secretsanta-db
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: secretsanta
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  backend:
    container_name: secretsanta-backend
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=secretsanta
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - db

volumes:
  postgres_data:
