# Generated by Django 5.0.6 on 2024-06-18 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrawParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='secretsanta.draw')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giving', to='secretsanta.participant')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiving', to='secretsanta.participant')),
            ],
            options={
                'unique_together': {('draw', 'giver', 'receiver')},
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cannot_receive_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='secretsanta.participant')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisting', to='secretsanta.participant')),
            ],
            options={
                'unique_together': {('participant', 'cannot_receive_from')},
            },
        ),
    ]
